version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    networks:
      - default
    environment:
      - "POSTGRES_USER=${POSTGRES_USER:?err}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}"
    ports:
      - "5432:5432"
    volumes:
      - "$HOME/svc/.data/postgres:/var/lib/postgresql/data"

networks:
  default:
    name: cicd
    external: true
